services:
  postgres:
    container_name: postgres
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      POSTGRES_USER: bd2
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: